version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_wallet
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: walletdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - wallet-net

volumes:
  mysql_data:

networks:
  wallet-net:
